# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tick < Formula
  desc "Terminal-native portfolio and market intelligence tool"
  homepage "https://github.com/squeakycheese75/tick"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squeakycheese75/tick/releases/download/v0.1.1/tick_0.1.1_darwin_amd64.tar.gz"
      sha256 "c1bd3cf58409caf443d03f63b571d843878f03f3b0a39a13ac0377cc8fcdb901"

      define_method(:install) do
        bin.install "tick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squeakycheese75/tick/releases/download/v0.1.1/tick_0.1.1_darwin_arm64.tar.gz"
      sha256 "2e3a032008dd538ecb5c21f105eeace0f8c72462c1d7f9e6d2d332d033a02367"

      define_method(:install) do
        bin.install "tick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/squeakycheese75/tick/releases/download/v0.1.1/tick_0.1.1_linux_amd64.tar.gz"
      sha256 "61554e25cf4272ceb895a59ee9c699a12ae2bb02c9e4b359d5e95dbf12823a64"
      define_method(:install) do
        bin.install "tick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/squeakycheese75/tick/releases/download/v0.1.1/tick_0.1.1_linux_arm64.tar.gz"
      sha256 "3218b4300a1a5b3c53c4937e99ccaa755dd7e222294cd54afc05c877a01211dd"
      define_method(:install) do
        bin.install "tick"
      end
    end
  end

  test do
    system "#{bin}/tick", "version"
  end
end
